name: build-rails-base
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        tag:
          - debian/3.2
    container:
      image: docker:git
      env:
        DOCKER_REPOSITORY: public.ecr.aws/degica/rails-base
        DOCKER_BUILDKIT: '1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-22.04
    steps:
    - name: prepare
      run: |-
        apk add --no-cache python3 py3-pip
        pip3 install --upgrade pip
        pip3 install awscli
    - name: workaround git security
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
    - name: setup
      run: git submodule update --init
    - name: build_and_push
      run: |-
        cd rails-base/${{ matrix.tag }}
        TAG_NAME=`echo "${{ matrix.tag }}" | sed 's/\//-/'`
        if [[ ${GITHUB_REF##*/} == 'master' ]]; then
            IMAGE_TAG=$TAG_NAME
        else
            IMAGE_TAG=test-${GITHUB_REF##*/}-$TAG_NAME # branch name for dev usecases
        fi
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/degica
        docker build . -t $DOCKER_REPOSITORY:$IMAGE_TAG --build-arg git_revision=$IMAGE_TAG --pull
        docker images
        docker push $DOCKER_REPOSITORY:$IMAGE_TAG
'on':
  push:
    branches:
    - '*'
